DROP TABLE IF EXISTS `LML_USER`;
CREATE TABLE `LML_USER` (
  `ID_` varchar(64) NOT NULL,
  `USER_NAME_` varchar(255) DEFAULT NULL,
  `PWD_` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

insert into LML_USER
values ('123456', 'TEST', 'GJTOVqhvpHtZlRNnRUUcNQ==');

DROP TABLE IF EXISTS `LML_USER_SESSION`;
CREATE TABLE `LML_USER_SESSION` (
  `USER_TOKEN_` varchar(255) NOT NULL,
  `ID_` varchar(64) DEFAULT NULL,
  `EXP_TIME_` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`USER_TOKEN_`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
